#!/bin/sh

rootcheck() {
    [ $(id -u) -eq 0 ] && return 0 || return 1
}

# naive networkcheck
networkcheck() {
    ping -c 2 voidlinux.org > /dev/null && return 0 || return 1
}

echo -e "${bold}Setting up zsh:${reset}"
printf "Run as root? \n"; rootcheck && echo [ok] || exit ; sleep 0.4
printf "Checking Connection: \n"; networkcheck && echo [ok] || exit ; sleep 0.4


# setting up zsh
# preparation
xbps-install -Syu
xbps-install -Sy git
rm -rf /etc/profile.d/bash.sh
rm -rf $HOME/.bash*
touch /etc/profile.d/zsh.sh
echo 'export ZDOTDIR="$HOME/.config/zsh"' >> /etc/profile.d/zsh.sh
runuser -l $SUDO_USER -c 'mkdir -p $HOME/.config/zsh"'


# .zshenv for environment variables
runuser -l $SUDO_USER -c 'touch $HOME/.config/zsh/.zshenv"'
runuser -l $SUDO_USER -c 'echo 'export XDG_CONFIG_HOME="$HOME/.config"' >> $HOME/.config/zsh/.zshenv"'
runuser -l $SUDO_USER -c 'mkdir -p $HOME/.cache/zsh"'
runuser -l $SUDO_USER -c 'echo 'export XDG_CACHE_DIR="$HOME/.cache"' >> $HOME/.cache"'


# .zprofile for autorunning commands on login
runuser -l $SUDO_USER -c 'touch $HOME/.config/zsh/.zprofile"'

# .zshrc for configuration and commands
runuser -l $SUDO_USER -c 'touch $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# GENERATED BY INSTALLER:" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# convenience aliases:" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias reboot="sudo reboot"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias poweroff="sudo poweroff"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias shutdown="sudo shutdown now"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias xi "sudo xbps-install"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias xr "sudo xbps-remove"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias xu "sudo xbps-install -Syu"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'alias xs "sudo xbps-query -Rs"' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# auto cd into typed directory:" >> $HOME/.config/zsh/.zshrc'
runuser -l $SUDO_USER -c 'echo "setopt autocd" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# enable colors:" >> $HOME/.config/zsh/.zshrc'
runuser -l $SUDO_USER -c 'echo "autoload -U colors && colors" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "change prompt:" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo 'PS1="%B%{$fg[red]%}[%{$fg[yellow]%}%n%{$fg[green]%}@%{$fg[blue]%}%M %{$fg[magenta]%}%~%{$fg[red]%}]%{$reset_color%}$%b "' >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# fix annoying stuff" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# disable ctrl-s to freeze terminal" >> $HOME/.config/zsh/.zshrc'
runuser -l $SUDO_USER -c 'echo "stty stop undef" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# move .zcompdump directory" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "autoload -Uz compinit" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "compinit -d ~/.cache/zsh/zcompdump-$ZSH_VERSION" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# add ctrl+a and ctrl+e support" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "bindkey -M viins '^a' beginning-of-line" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "bindkey -M viins '^e' end-of-line" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# configure shell history" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "HISTFILE=$HOME/.cache/zsh/histfile.txt" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "HISTSIZE=10000" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "SAVEHIST=10000" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo -e "\n" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "# import plugins" >> $HOME/.config/zsh/.zshrc'
runuser -l $SUDO_USER -c 'mkdir -p $HOME/.local/share/zsh/plugins/"'
runuser -l $SUDO_USER -c 'git clone --depth 1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git $HOME/.local/share/zsh/plugins/zsh-syntax-highlighting"'
runuser -l $SUDO_USER -c 'git clone --depth 1 -- https://github.com/zsh-users/zsh-autosuggestions.git /tmp/installer/zsh/zsh-autosuggestions"'
runuser -l $SUDO_USER -c 'echo "source $HOME/.local/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" >> $HOME/.config/zsh/.zshrc"'
runuser -l $SUDO_USER -c 'echo "source $HOME/.local/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh" >> $HOME/.config/zsh/.zshrc"'
xbps-install -Sy zsh
runuser -l $SUDO_USER -c 'chsh -s /bin/zsh $USER"'

echo "DONE!"